//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFM_Reg_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class adherents
    {
        public adherents()
        {
            this.Emprunts = new HashSet<Emprunts>();
        }
    
        public int CodeAdh { get; set; }
        public string NomAdh { get; set; }
        public string PrenomAdh { get; set; }
    
        public virtual ICollection<Emprunts> Emprunts { get; set; }
    }
}
