//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFM_Reg_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprunts
    {
        public int NumEmp { get; set; }
        public Nullable<int> CodeAdh { get; set; }
        public Nullable<int> CodeFilm { get; set; }
        public Nullable<System.DateTime> DateEmp { get; set; }
        public Nullable<System.DateTime> DateRet { get; set; }
    
        public virtual adherents adherents { get; set; }
        public virtual Films Films { get; set; }
    }
}
